// import './global.css'; // ✅ correct relative path

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <header style={{backgroundColor: 'skyblue', height: '60px'}}>Header</header> */}
      <body>{children}</body>
      {/* <footer style={{backgroundColor: 'gray', height: '60px'}}>Footer</footer> */}
    </html>
  )
}
